# Generated by Django 5.2.15 on 2026-06-20 14:31

import django.db.models.deletion
import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "upload_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("total_chunks", models.IntegerField()),
                ("file_size", models.BigIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("chunk_size", models.IntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FileRecord",
            fields=[
                (
                    "file_id",
                    models.CharField(
                        default=files.models.generate_short_uuid,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("file_path", models.CharField(max_length=500)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="files.uploadsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChunkUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("chunk_path", models.CharField(max_length=500)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="files.uploadsession",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
                "unique_together": {("upload", "chunk_index")},
            },
        ),
    ]
